--- # Exercise: The 'Fetch' Module
- hosts: torbsch1
  become: yes
  gather_facts: yes
  tasks:
  - name: Copy remote hosts file
    fetch:
      src: /etc/hosts
      dest: /home/ansible/prefix-{{ ansible_hostname}}
      flat: yes