--- # Exercise: The 'HTPasswd' Module
- hosts: torbsch1
  become: yes
  gather_facts: no
  tasks:
  - name: Install Exercise The python-passlib package
    apt: name=python-passlib state=latest update_cache=yes
  - name: Adds usergroup 'test'
    group: name=test state=present
  - name: Create User 'test'
    user:
      name: test
      password: test
      group: test
      append: yes
  - name: Create HTPasswd-File for User test
    htpasswd:
      path: /etc/apache2/.htpasswd
      name: test
      password: test
      group: test
      mode: 0640