--- # Example Loop Playbook
- hosts: torbsch1
  become: yes
  gather_facts: no
  tasks:
  - name: add user1, user2, user3
    user: name={{ item }} state=present
    with_items:
      - user1
      - user2
      - user3