--- # Build an Apache Web Server on RedHat
- hosts: torbsch3
  become: yes
  gather_facts: no
  connection: ssh
  vars:
    apache_dir: /var/www/html/sample
    apache_configration_path: /etc/httpd
    fqdn: http://torbsch3.mylabserver.com
    dir_mode: 0755
    file_mode: 0644
    service_name: httpd
  tasks:
  - name: Install Apache Web Server on Debian
    yum: name='{{ service_name }}' state=latest
  - name: Create Web Server Directory
    file: 
      path: '{{ apache_dir }}'
      state: directory
      mode: '{{ dir_mode }}'    
  - name: Configurate Apache on RedHat
    file: 
      src: conf/apache.conf
      dest: "{{ apache_configration_path }}/conf/httpd.conf"
      group: root
      mode: '{{ file_mode }}'
  - name: Create the VHOST.D directory on the remote host on RedHat
    file:
      path: "{{ apache_configration_path }}/vhost.d"
      state: directory
      mode: '{{ file_mode }}'
  - name: Copy code of the site to new directory
    copy:
      src: files/index.html
      dest: "{{ apache_dir }}"
      mode: '{{ file_mode }}'
  - name: Copy the default vhost configuration file on RedHat
    copy:
      src: files/default.conf.template
      dest: "{{ apache_configration_path }}/vhost.d/default.conf"
      owner: root
      group: root
      mode: '{{ file_mode }}'
  - name: Start the apache service on RedHat
    service: name='{{ service_name }}' state=restarted
  - name: Test the web server
    shell: curl "{{ fqdn }}"
    register: result
  - name: DisplayResult
    debug: var=result