--- # Exercise: The 'Notify' Module
- hosts: torbsch3
  connection: ssh
  become: yes
  gather_facts: no
  
  tasks:
  - name: install apache
    yum: name=httpd state=present
    notify: Start Apache Service
  handlers:
  - name: Start Apache Service
    service: name=httpd state=restarted