--- # Exercise: The Pause Module
- hosts: torbsch1
  become: yes
  gather_facts: no
  tasks:
  - name: Install Apache
    apt: name=apache2 state=latest update_cache=yes
  - name: Pause
    pause:
     prompt: Make sure installation is complete...
  - name: Install Lynx
    apt: name=lynx state=present update_cache=yes