--- # Exercise: The 'Service' Module
- hosts: torbsch3
  become: yes
  gather_facts: no
  tasks:
  - name: Install Apache
    yum: name=httpd state=latest update_cache=yes
    notify: Enables Apache Service to start on system boot
  handlers:
  - name: Enables Apache Service to start on system boot
    service: name=httpd enabled=yes state=restarted