--- # Exercise: The 'SetFact' Module
- hosts: torbsch1
  become: yes
  gather_facts: no
  vars:
    playbook_version: 1.0
  tasks:
  - name: Sets a singlefact
    set_fact:
      singlefact: foobar
  - debug: msg={{ playbook_version }}
  - debug: msg={{ singlefact }}