--- # Exercise: The 'Shell' Module
- hosts: torbsch1
  become: yes
  gather_facts: no
  tasks:
  - name: Execute the uptime command and log it
    shell: uptime >> /home/ansible/uptime.log
    args:
      chdir: logs/
      creates: uptime.log
