--- # Exercise: Playbooks - Until
- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: Install Apache
    apt: name=apache2 state=latest update_cache=yes
    tags: 
    - packages
  - name: Check, if Apache Service is running
    shell: systemctl status apache2
    register: result
    until: result.stdout.find("active (running)") != -1
    retries: 5
    delay: 5
    tags:
    - verification
  - debug: var=result
    tags:
    - verification