--- # Exercise: The WaitFor Module
- hosts: torbsch1
  become: yes
  gather_facts: no
  tasks:
  - name: Install Tomcat
    apt: name=tomcat8 state=latest update_cache=yes
  - name: Wait for Port 8080 running
    wait_for:
      port: 8080
      state: started
  - name: Verifiy Lynx is installed
    apt: name=lynx state=present update_cache=yes