- hosts: torbsch1
  connection: ssh
  become: yes
  gather_facts: no
  tasks:
  - name: Capture a pre-task timestamp
    shell: date > /home/ansible/playbook_start.yml
  - name: Install apache, telnet and lynx
    apt: name={{item}} state=latest update_cache=yes
    with_items:
    - apache2
    - telnet
    - lynx
  - name: Write Log of all installed packages
    shell: apt list > /home/ansible/installedpackages.log
  - name: Capture a post-task timestamp
    shell: date > /home/ansible/playbook_end.yml