- hosts: torbsch1
  connection: ssh
  become: yes
  gather_facts: no
  tasks:
  - name: Capture a pre-task timestamp
    shell: date
    register: playbook_start
  - debug: var=playbook_start
  - name: Install telnet and lynx
    apt: name={{item}} state=latest update_cache=yes
    with_items:
    - telnet
    - lynx
  - name: Install apache
    apt: name=apache2 state=latest update_cache=yes
    notify: Restart Apache Service after Installation
  - name: Write Log of all installed packages
    shell: apt list
    register: installed
  - debug: var=installed
  - name: Capture a post-task timestamp
    shell: date
    register: playbook_end
  - debug: var=playbook_end
  handlers:
  - name: Restart Apache Service after Installation
    service: name=apache2 state=restarted
